### ISSUE TITLE
Duplication in documentation

### ISSUE THREAD

**Issue by HillaShx** [cocmd/cocmd#59]
Having documentation in both the README file and its own site creates more confusion than it does clarity. It's also double the work for half of the value. My suggestion is to only maintain the docs and in the README link to the docs. I'll be working on a PR for this.

Example of diff in the docs between README and the docs site:

<img width="488" alt="Screenshot 2023-11-03 at 11 33 14" src="https://github.com/cocmd/cocmd/assets/44138955/3dbc307b-bfdc-4033-9d70-4b35d343c4b9">
<img width="391" alt="Screenshot 2023-11-03 at 11 33 27" src="https://github.com/cocmd/cocmd/assets/44138955/4c2e8acd-22b4-4b46-9375-d3ba6260668b">

**Comment by mzsrtgzr2** [comment]
@HillaShx great idea! thank you!
