### ISSUE TITLE
git.commit-push flow

### ISSUE THREAD

**Issue by HillaShx** [cocmd/cocmd#70]
As a developer, I rarely want to commit all the files (some files are local config, some files I added something for dev purposes, etc.). My suggestion is, letting the user select the files they want to commit.
I had in mind something similar to the selection menu we show the user in `cocmd install`
<img width="262" alt="Screenshot 2023-11-04 at 12 38 58" src="https://github.com/cocmd/cocmd/assets/44138955/241c3d42-c617-4e2e-9dfe-164bc0b6b3a5">

It can list all of the changed files (I think there's a file in the .git directory that keeps track of changed files), and lets you select the ones you wanna commit.
I personally use `git add -p` that shows the changes in blocks of code, but I couldn't think of a non-complex way of doing that, so this is my compromise.

**Tests**

**Docs**
Requires addition [Here](https://cocmd.org/docs/packages/from_hub/git)

**Comment by mzsrtgzr2** [comment]
@HillaShx Great! I thought about adding the "hub" suggestions in https://github.com/cocmd/hub/issues

**Comment by HillaShx** [comment]
Sure thing! :)
